<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>pets_simulation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="index.html" />
    <Content Include="styles.css" />
    <Content Include="app.js" />
    <Content Include="content.js" />
    <Content Include="d3.min.js" />
    <Content Include="README.md" />
  </ItemGroup>

</Project>
